language: python
python:
      - "2.7"
      - "3.4"
      - "3.5"
      - "3.6"
      - "3.7-dev"
      - "pypy"
      - "pypy3.3-5.2-alpha1"

matrix:
    allow_failures:
        - python: "3.7-dev"
        - python: "pypy3.3-5.2-alpha1"

install: pip install tox-travis
script: tox

